# 启动配置
spring:
  profiles:
    active: dev

---
# root的用户名
root-username: root
# 登录权限
login-perms: root|admin
# tomcat配置
server:
  port: 9786
# 匿名函数配置
func-link:
  logger:
    enable-log: true
    file-name: admin-system
    date-format: yyyy-MM-dd HH:mm:ss
# mybatis 配置
mybatis:
  type-aliases-package: com.yiur.admin.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
# spring 配置
spring:
  profiles: dev
  application:
    # 多个 dept 服务名称一致
    name: admin
  datasource:
    # druid 数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://127.0.0.1:3306/admin-system?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: 123456
  # Redis 配置
  redis:
    host: 127.0.0.1
    port: 6380
    password: 123456
    timeout: 15000
  # quartz 配置
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    scheduler-name: adminSystemScheduler
  # servlet 配置
  servlet:
    # 文件上传配置
    multipart:
      # 上传总大小
      max-request-size: 200MB
      # 上传文件单个大小
      max-file-size: 50MB
  # mvc 配置
  mvc:
    # date 处理
    format:
      date: yyyy-MM-dd HH:mm:ss
    converters:
      preferred-json-mapper: jackson
  # json处理
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 开启热部署
  devtools:
    restart:
      # 是否开发
      enabled: true
      # 排除
      exclude: WEB-INF/**
      # 重启目录
      additional-paths: src/main/java

---
# root的用户名
root-username: root
# 登录权限
login-perms: root|admin
# tomcat配置
server:
  port: 9786
# 匿名函数配置
func-link:
  logger:
    enable-log: true
    file-name: admin-system
    date-format: yyyy-MM-dd HH:mm:ss
# mybatis 配置
mybatis:
  type-aliases-package: com.yiur.admin.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
# spring 配置
spring:
  profiles: test
  application:
    # 多个 dept 服务名称一致
    name: admin
  datasource:
    # druid 数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://127.0.0.1/admin-system?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: 123456
  # Redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 15000
  # quartz 配置
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    scheduler-name: adminSystemScheduler
  # servlet 配置
  servlet:
    # 文件上传配置
    multipart:
      # 上传总大小
      max-request-size: 200MB
      # 上传文件单个大小
      max-file-size: 50MB
  # mvc 配置
  mvc:
    # date 处理
    format:
      date: yyyy-MM-dd HH:mm:ss
    converters:
      preferred-json-mapper: jackson
  # json处理
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 开启热部署
  devtools:
    restart:
      # 是否开发
      enabled: true
      # 排除
      exclude: WEB-INF/**
      # 重启目录
      additional-paths: src/main/java